version: "3.9"
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  mar:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
